## 📘 Data Challenge 11 – Dash App with a Pie or Scatter Plot

Assignment Type: Partner/Group 
Estimated Time: 45–60 minutes

---
### 🎯 Targeted KSBs (Knowledge, Skills, and Behaviors)
S6 – Creates dynamic visualizations using Python (Plotly)

S7 – Designs clear dashboards using Dash

K10 – Chooses appropriate chart types for data and audience

B6 – Applies structured thinking to turn analysis into a dashboard app

---

### 📊 Scenario:
You’re helping an athletic director create a quick dashboard for just **five sports**. She wants to better understand how men’s and women’s revenue compare across a few programs. Your job is to make a simple Dash app with a pie chart or scatter plot showing the difference.

---
### ✅ Your Task (Step-by-Step)

- Load the sports.csv file using pandas.

- Drop missing values in the sports, rev_men, and rev_women columns.

- Pick 5 unique sports (your choice!) and filter the DataFrame to only include those.

    - Example: "Basketball", "Tennis", "Soccer", "Volleyball", "Golf"

- Create a new column called "Total_Revenue" by adding men’s and women’s revenue.

- Create either a pie chart or a scatter plot:

In [22]:
# Import packages 

import dash
from dash import html, dcc
import pandas as pd
import plotly.express as px
import dash_bootstrap_components as dbc

In [6]:
# Load and filter the data
df = pd.read_csv('/Users/Marcy_Student/Desktop/marcy/DA2025_Lectures/Mod2/data/sports.csv')
df = df[["sports", "rev_men", "rev_women"]].dropna()

/var/folders/bs/gtwb0lj97nb4v95968dmfzww0000gp/T/ipykernel_46848/3679468179.py:2: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('/Users/Marcy_Student/Desktop/marcy/DA2025_Lectures/Mod2/data/sports.csv')

In [9]:
# Pick 5 sports
top5 = ["Basketball", "Tennis", "Soccer", "Volleyball", "Golf"]
#Copying the dataframe to not overwrite the original 
df_5 = df[df["sports"].isin(top5)].copy()
df_5

            sports    rev_men  rev_women
1       Basketball  1211095.0   748833.0
7           Tennis    78274.0   131145.0
11      Basketball  4189826.0  1966556.0
13            Golf   407728.0   346987.0
15          Soccer  1062855.0   944819.0
...            ...        ...        ...
132299      Tennis   132323.0   141556.0
132317  Basketball   104775.0    62345.0
132318  Basketball   549740.0   547230.0
132321        Golf   221193.0   224243.0
132322      Soccer   652950.0   357251.0

[26007 rows x 3 columns]

In [11]:
# Create new column called Total_Revenue that adds up the men and women's revenue columns
df_5["Total_Revenue"] = df['rev_men'] + df['rev_women']
df_5

            sports    rev_men  rev_women  Total_Revenue
1       Basketball  1211095.0   748833.0      1959928.0
7           Tennis    78274.0   131145.0       209419.0
11      Basketball  4189826.0  1966556.0      6156382.0
13            Golf   407728.0   346987.0       754715.0
15          Soccer  1062855.0   944819.0      2007674.0
...            ...        ...        ...            ...
132299      Tennis   132323.0   141556.0       273879.0
132317  Basketball   104775.0    62345.0       167120.0
132318  Basketball   549740.0   547230.0      1096970.0
132321        Golf   221193.0   224243.0       445436.0
132322      Soccer   652950.0   357251.0      1010201.0

[26007 rows x 4 columns]

In [19]:
# Make your pie or scatteplot using plotly 

fig = px.pie(df_5, names='sports', hole=0.2, color='sports',title='Sports repartition',template='plotly_dark')
fig.show()

In [36]:
# Make the App -- DO NOT RUN THIS CELL YET It may give you a "port already in use error if you do"

app = dash.Dash(__name__, external_stylesheets=[dbc.themes.BOOTSTRAP])
app.title = 'MY DASH APP'

app.layout = dbc.Container([
    dbc.Row(
        dbc.Col(html.H1(children='Revenue Analysis for 5 Sports'), class_name='text-center bg-light my-5', width=10)),
    dbc.Row([
        dbc.Col(dcc.Graph(figure=fig,id='my_pie',className='bg-light d-flex'), width=20)]),
    dbc.Row([
        dbc.Col(html.Button('JUST DO IT', id='My_button', className='btn-lg my-3'),width='4'),
        dbc.Col(dcc.Slider(0, 4, marks={i: f'Label{i}' for i in range(5)}, value=3))
    ])
])

if __name__ == '__main__':
    app.run(debug=True)

### Copy and paste the code in this notebook into a file called `app.py` and run that file; then go to your localhost address:  http://localhost:8050/ to see the updated visual