# Data Challenge: Creating Interactive Plotly Visuals

## Targeted KSBs (Knowledge, Skills, and Behaviors)

- **S6** – Demonstrates mastery in creating dynamic visualizations using Python (Plotly)
- **K10** – Applies chart selection principles based on data types, variables, and audience needs
- **S12** – Performs comprehensive data exploration to uncover patterns and relationships

---

## Dataset Description:

This dataset contains information about various Indian sweets, including their ingredients, preparation time, and flavor profile.  You can read more about the data [Here](https://www.kaggle.com/datasets/nehaprabhavalkar/indian-food-101?select=indian_food.csv)

---

## Task 1: Plot a Scatter Plot of Prep Time vs Cook Time
### Objective:
Create a line chart showing the relationship between **prep time** and **cook time** for each food item. Use Plotly to visualize these two variables and identify any patterns.

### Instructions:
1. **Load the dataset** using `pandas`.
2. Use **Plotly Express** to create a **scatterplot**.
3. Set **prep_time** on the x-axis and **cook_time** on the y-axis.
4. **Label** the axes appropriately and add a **title** for clarity.

In [12]:
#Run this cell without changes 
import pandas as pd 
import plotly.express as px

In [13]:
# Read in the data (data/indian_food.csv) -- Hint use pandas to read in the CSV 

df = pd.read_csv('/Users/Marcy_Student/Desktop/marcy/DA2025_Lectures/Mod2/data/indian_food.csv')
df.head()

,name,ingredients,diet,prep_time,cook_time,flavor_profile,course,state,region
0,Balu shahi,"Maida flour, yogurt, oil, sugar",vegetarian,45,25,sweet,dessert,West Bengal,East
1,Boondi,"Gram flour, ghee, sugar",vegetarian,80,30,sweet,dessert,Rajasthan,West
2,Gajar ka halwa,"Carrots, milk, sugar, ghee, cashews, raisins",vegetarian,15,60,sweet,dessert,Punjab,North
3,Ghevar,"Flour, ghee, kewra, milk, clarified butter, su...",vegetarian,15,30,sweet,dessert,Rajasthan,West
4,Gulab jamun,"Milk powder, plain flour, baking powder, ghee,...",vegetarian,15,40,sweet,dessert,West Bengal,East

In [9]:
df.dtypes

name              object
ingredients       object
diet              object
prep_time          int64
cook_time          int64
flavor_profile    object
course            object
state             object
region            object
dtype: object

In [16]:
# Create a scatterplot of prep_time on X-axis & cook_time on Y-axis 

fig = px.scatter(df, x="prep_time", y="cook_time", title="Scatter of Prep_time over Cook_time",color="prep_time")

# Show the plot
fig.show()

### What insights did you get from Task 1? (Double-click to type answer)

## Task 2: Bar Chart of Cook Time by Region

### Objective:
Create a bar chart that shows the average cook time for each region. This will help us understand the cooking time distribution across different regions.  **There is a "weird" bar in the chart why is that the case??**


### Instructions:
- Group the data by the region. (Hint:  may need a df.groupby() method here!)

- Calculate the average cook time for each region.

- Create a bar chart using Plotly to show this average cook time for each region.

- Label the axes and title the chart.

In [24]:
# Task 2: Create a bar chart showing the average cook time by region
# Fill in the code to group by region and calculate the average cook time
df_region_avg = df.groupby('region')['cook_time'].mean().reset_index()

# Create the bar chart
fig = px.bar(df_region_avg, x='region', y='cook_time', title="Average Cook Time by Region",color='region',
             hover_name='cook_time', template='plotly_dark')

# Show the plot
fig.show()

### What insights did you get from Task 2? (Double-click to type answer)

## Task 3: Pie Chart of Flavor Profile Distribution

### Objective:
Create a pie chart showing the distribution of flavor profiles (e.g., sweet, savory) across the dataset.

### Instructions:
- Use Plotly Express to create a pie chart.

- Plot the flavor_profile column, which will show the distribution of flavor types.

- Ensure the chart is labeled clearly.

In [25]:
df.head(7)

,name,ingredients,diet,prep_time,cook_time,flavor_profile,course,state,region
0,Balu shahi,"Maida flour, yogurt, oil, sugar",vegetarian,45,25,sweet,dessert,West Bengal,East
1,Boondi,"Gram flour, ghee, sugar",vegetarian,80,30,sweet,dessert,Rajasthan,West
2,Gajar ka halwa,"Carrots, milk, sugar, ghee, cashews, raisins",vegetarian,15,60,sweet,dessert,Punjab,North
3,Ghevar,"Flour, ghee, kewra, milk, clarified butter, su...",vegetarian,15,30,sweet,dessert,Rajasthan,West
4,Gulab jamun,"Milk powder, plain flour, baking powder, ghee,...",vegetarian,15,40,sweet,dessert,West Bengal,East
5,Imarti,"Sugar syrup, lentil flour",vegetarian,10,50,sweet,dessert,West Bengal,East
6,Jalebi,"Maida, corn flour, baking soda, vinegar, curd,...",vegetarian,10,50,sweet,dessert,Uttar Pradesh,North

In [64]:
df_grouped= df.groupby('flavor_profile').count().reset_index()
df_grouped.head()
df_grouped.head()

,flavor_profile,name,ingredients,diet,prep_time,cook_time,course,state,region,value
0,-1,29,29,29,29,29,29,29,29,0
1,bitter,4,4,4,4,4,4,4,4,0
2,sour,1,1,1,1,1,1,1,1,0
3,spicy,133,133,133,133,133,133,133,133,0
4,sweet,88,88,88,88,88,88,88,87,0

In [67]:
# Task 3: Create a pie chart showing the flavor profile distribution
# Fill in the code to create the pie chart -- look up documentation if needed 
fig = px.pie(df_grouped,names='flavor_profile',
             values='name',
             hole=0.3, template='plotly_dark',title='Pie Chart of Flavors',
             hover_name='flavor_profile')

# Show the plot
fig.show()

### What insights did you get from Task 3? (Double-click to type answer)

The spicy flavour is the most popular with over 50% of the total profiles, in the other hand, the sour one is the least popular, onlyn 1 unit, closely followed by bitter flavour with only 4 units,1,57%.
88 out of total, 34,5 % of the flavour is sweet, which represent the second most popular.